### ISSUE TITLE
MacOS Catalina Javascript error on Launch

### ISSUE THREAD

**Issue by PUmacTool** [Seeed-Solution/SenseCAP-Node-Configuration-Tool#9]
whenever the tool is launched on MacOS Catalina (10.15.6), an JavaScript uncaught exception error prevents the window from opening.

**Comment by KillingJacky** [comment]
A Catalina launch error had been fixed at 14cabf758e1a59809d2a0d63258fa11a179dc3fd which is version 1.0.3.
We've tested on MacOS 10.15.7, works well.

![image](https://user-images.githubusercontent.com/5130185/104446663-bf407680-55d5-11eb-9e2e-c38c643296c3.png)

Could you please post the screenshot of the error?

**Comment by PUmacTool** [comment]
Thank you.  I was using the linked version in the documentation, 1.0.2.  I've downloaded 1.0.4 and it launches w/o error.
